# Generated by Django 3.0.7 on 2020-09-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('userCode', models.CharField(max_length=30, verbose_name='用户账号')),
                ('userPassword', models.CharField(max_length=30, verbose_name='用户密码')),
                ('logo', models.ImageField(default='logo/logo.jpg', upload_to='logo')),
                ('userName', models.CharField(max_length=30, verbose_name='用户名称')),
                ('role', models.CharField(max_length=10, verbose_name='用户角色')),
                ('createTime', models.CharField(max_length=30, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
